# Necessário para as teclas de mouse (&mkp, &mmv, &msc) do toque-duplo funcionarem
CONFIG_ZMK_POINTING=y

# Força alimentação contínua na matriz física
CONFIG_ZMK_EXT_POWER=y

# Força o envio das teclas pelo cabo USB quando conectado
CONFIG_ZMK_USB=y
